# Generated by Django 5.0 on 2023-12-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='class_name',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='faculty',
            new_name='faculty_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='professor',
            new_name='professor_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='school',
            new_name='school_id',
        ),
    ]
