# Generated by Django 5.0 on 2023-12-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_class_name_post_class_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='class_id',
            new_name='_class',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='professor_id',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='school_id',
            new_name='school',
        ),
    ]
